name:                Quoridor
version:             0.1.0.0
github:              "y-tsune/Quoridor"
license:             BSD3
author:              "Yutaro Tsunekawa"
maintainer:          "tsunekawa@ueda.info.waseda.ac.jp"
copyright:           "2020 Yutaro Tsunekawa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/y-tsune/Quoridor#readme>

dependencies:
- base >= 4.7 && < 5
- parallel
- repa >= 3.2 && < 3.5
- mtl

library:
  source-dirs: src

executables:
  Quoridor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Quoridor

tests:
  Quoridor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Quoridor
